[versions]
# üß± Core & Build
agp = "8.13.1"
kotlin = "2.2.20"
ksp = "2.3.0"
secretsGradlePlugin = "2.0.1"

# ü§ñ AndroidX
coreKtx = "1.17.0"
lifecycle = "2.9.4"
activity = "1.11.0"
appCompat = "1.7.1"

# üé® Jetpack Compose
composeBom = "2025.11.00"
navigationCompose = "2.9.6"

# üåê Networking
ktor = "3.3.2"
kotlinxSerialization = "1.9.0"
coroutines = "1.10.2"

# üñºÔ∏è Image Loading
coil = "2.7.0"
palette = "1.0.0"

# üß™ Testing
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
testCoreKtx = "1.7.0"
mockk = "1.14.6"
turbine = "1.2.1"
leakCanary = "2.14"

# üíâ Dependency Injection
koin = "4.1.1"

# Timber (Logging)
timber = "5.0.1"

# Room
room = "2.8.3"

# Security
sqlcipher = "4.5.4"
sqlite = "2.6.1"
security = "1.1.0"

# Paging
paging = "3.3.6"

[libraries]
# ---------- üß± Core & Kotlin ----------
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appCompat" }

# ---------- üß† State, Lifecycle & ViewModel ----------
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }

# ---------- üíâ Dependency Injection (Koin) ----------
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-android = { module = "io.insert-koin:koin-android" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose" }
koin-androidx-compose-navigation = { module = "io.insert-koin:koin-androidx-compose-navigation" }


# ---------- üé® Jetpack Compose UI ----------
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }

# ---------- üó∫Ô∏è Navigation ----------
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }

# ---------- üåê Networking (Ktor & Serialization) ----------
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-android = { group = "io.ktor", name = "ktor-client-android", version.ref = "ktor" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }

# ---------- üñºÔ∏è Image Loading ----------
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
androidx-palette = { group = "androidx.palette", name = "palette-ktx", version.ref = "palette" }

# ---------- üß™ Testing ----------
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
test-mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
test-turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
paging-test = { module = "androidx.paging:paging-common" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
koin-test = { module = "io.insert-koin:koin-test" }
androidx-test-coreKtx = { module = "androidx.test:core-ktx", version.ref = "testCoreKtx" }
android-leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakCanary" }

# Logging
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

# Room
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-paging = {module = "androidx.room:room-paging", version.ref = "room"}


# Security
sqlcipher = { module = "net.zetetic:android-database-sqlcipher", version.ref = "sqlcipher" }
sqlite-ktx = { module = "androidx.sqlite:sqlite-ktx", version.ref = "sqlite" }
security-crypto = { module = "androidx.security:security-crypto", version.ref = "security" }

# Paging
androidx-paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "paging" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "paging" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
secrets-gradle = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "secretsGradlePlugin" }
